export const MAX_MESSAGE_LENGTH = 50000;
export const MAX_FILE_SIZE = 10 * 1024 * 1024; // 10MB
export const PROFILE_GATE_THRESHOLD = 0.7;
export const CHAT_RATE_LIMIT = 30; // per minute
export const CHAT_STORAGE_KEY = "pmguide-chat-history";
export const INTERVIEW_STORAGE_KEY = "pmguide-interview-history";
export const BRANCH_STORAGE_KEY = "pmguide-resume-branches";
export const MAX_BRANCHES = 5;
export const BRANCH_CHAT_MAX_MESSAGES = 20;
export const BRANCH_RATE_LIMIT = 10; // per minute
export const RESUME_UPLOAD_KEY = "pmguide-resume-upload";
export const RESUME_CRITIQUE_KEY = "pmguide-resume-critique";
export const RESUME_GENERATE_KEY = "pmguide-resume-generate";
export const INTERVIEW_HISTORY_KEY = "pmguide-interview-lab-history";
export const INTERVIEW_RATE_LIMIT = 15;
export const MAX_INTERVIEW_HISTORY = 30;
export const NEGOTIATE_HISTORY_KEY = "pmguide-negotiate-history";
export const NEGOTIATE_STORAGE_KEY = "pmguide-negotiate-session";
export const NEGOTIATE_RATE_LIMIT = 10;
export const MAX_NEGOTIATE_HISTORY = 20;
export const NEGOTIATE_COACH_STORAGE_KEY = "pmguide-negotiate-coach";
export const MAX_SIMULATOR_TURNS = 20;
export const NEGOTIATE_CRAFTER_STORAGE_KEY = "pmguide-negotiate-crafter";
export const INTERVIEW_ASK_EXPERT_STORAGE_KEY = "pmguide-interview-ask-expert";
export const OUTREACH_STORAGE_KEY = "pmguide-outreach-drafts";
export const MAX_OUTREACH_DRAFTS = 10;
export const MAX_OUTREACH_MESSAGES = 20;
