"use client";

import { useState, useRef, useEffect, useCallback } from "react";
import { useProfile } from "@/stores/profile-context";
import type { OutreachContext, OutreachMessage } from "@/types/outreach";

interface OutreachActiveProps {
  draftId: string;
  context: OutreachContext;
  messages: OutreachMessage[];
  onSetMessages: (draftId: string, messages: OutreachMessage[]) => void;
  onBack: () => void;
}

function extractMessage(text: string): string | null {
  const start = text.indexOf("---MESSAGE---");
  const end = text.indexOf("---END---");
  if (start === -1 || end === -1 || end <= start) return null;
  return text.substring(start + "---MESSAGE---".length, end).trim();
}

const AUDIENCE_LABELS: Record<string, string> = {
  "hiring-manager": "Hiring Manager",
  recruiter: "Recruiter",
  referral: "Referral",
};

export function OutreachActive({
  draftId,
  context,
  messages,
  onSetMessages,
  onBack,
}: OutreachActiveProps) {
  const { state: profileState } = useProfile();
  const [input, setInput] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [copiedIndex, setCopiedIndex] = useState<number | null>(null);
  const [contextExpanded, setContextExpanded] = useState(false);
  const chatEndRef = useRef<HTMLDivElement>(null);
  const chatContainerRef = useRef<HTMLDivElement>(null);
  const isNearBottomRef = useRef(true);
  const hasAutoGeneratedRef = useRef(false);

  const handleScroll = useCallback(() => {
    const el = chatContainerRef.current;
    if (!el) return;
    isNearBottomRef.current =
      el.scrollHeight - el.scrollTop - el.clientHeight < 100;
  }, []);

  useEffect(() => {
    if (isNearBottomRef.current) {
      chatEndRef.current?.scrollIntoView({ behavior: "smooth" });
    }
  }, [messages]);

  const handleCopy = useCallback(async (text: string, index: number) => {
    const msg = extractMessage(text);
    const toCopy = msg ?? text;
    try {
      await navigator.clipboard.writeText(toCopy);
      setCopiedIndex(index);
      setTimeout(() => setCopiedIndex(null), 2000);
    } catch {
      // silent
    }
  }, []);

  const sendMessage = useCallback(
    async (text: string, currentMessages: OutreachMessage[]) => {
      if (isLoading) return;

      const userMsg: OutreachMessage = { role: "user", content: text };
      const newMessages = [...currentMessages, userMsg];
      onSetMessages(draftId, newMessages);
      isNearBottomRef.current = true;
      setIsLoading(true);

      try {
        const res = await fetch("/api/chat", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            message: text,
            section: "outreach",
            conversationHistory: currentMessages,
            profileSnapshot: profileState.profile,
            outreachContext: context,
          }),
        });

        if (!res.ok) {
          onSetMessages(draftId, [
            ...newMessages,
            { role: "assistant", content: "Sorry, something went wrong. Please try again." },
          ]);
          setIsLoading(false);
          return;
        }

        const reader = res.body?.getReader();
        if (!reader) {
          setIsLoading(false);
          return;
        }

        const decoder = new TextDecoder();
        let fullText = "";

        while (true) {
          const { done, value } = await reader.read();
          if (done) break;

          const chunk = decoder.decode(value, { stream: true });
          const lines = chunk.split("\n");

          for (const line of lines) {
            if (!line.startsWith("data: ")) continue;
            const data = line.slice(6);
            if (data === "[DONE]") continue;

            try {
              const parsed = JSON.parse(data);
              if (parsed.type === "text") {
                fullText += parsed.text;
                onSetMessages(draftId, [
                  ...newMessages,
                  { role: "assistant", content: fullText },
                ]);
              }
            } catch {
              // skip
            }
          }
        }

        if (!fullText) {
          onSetMessages(draftId, [
            ...newMessages,
            { role: "assistant", content: "I didn't get a response. Please try again." },
          ]);
        }
      } catch {
        onSetMessages(draftId, [
          ...newMessages,
          { role: "assistant", content: "Network error. Please try again." },
        ]);
      }
      setIsLoading(false);
    },
    [isLoading, draftId, profileState.profile, context, onSetMessages]
  );

  // Auto-generate on first load (no messages yet)
  useEffect(() => {
    if (messages.length === 0 && !hasAutoGeneratedRef.current) {
      hasAutoGeneratedRef.current = true;
      const recipientPart = context.recipientName ? ` to ${context.recipientName}` : "";
      const purposePart = context.purpose ? ` Context: ${context.purpose}` : "";
      const prompt =
        context.messageFormat === "linkedin"
          ? `Write a LinkedIn ${context.audienceType === "referral" ? "message" : "connection request"}${recipientPart} for the ${context.jobTitle || "PM"} role at ${context.company || "this company"}.${purposePart}`
          : `Write an outreach email${recipientPart} for the ${context.jobTitle || "PM"} role at ${context.company || "this company"}.${purposePart}`;
      sendMessage(prompt, []);
    }
  }, [messages.length, context, sendMessage]);

  const handleSend = useCallback(() => {
    const text = input.trim();
    if (!text || isLoading) return;
    setInput("");
    sendMessage(text, messages);
  }, [input, isLoading, messages, sendMessage]);

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  return (
    <div className="space-y-4" data-testid="outreach-active">
      <div className="flex items-center justify-between">
        <button
          type="button"
          onClick={onBack}
          className="text-sm text-slate-500 hover:text-slate-700"
        >
          &larr; Back to home
        </button>
      </div>

      <div>
        <h2 className="text-xl font-semibold text-slate-800">
          Outreach Message
        </h2>
        <p className="mt-1 text-sm text-slate-500">
          Refine your message with follow-up instructions, then copy and send.
        </p>
      </div>

      {/* Collapsible context */}
      <div className="rounded-lg border border-slate-200 bg-white">
        <button
          type="button"
          onClick={() => setContextExpanded(!contextExpanded)}
          className="flex w-full items-center justify-between px-4 py-3 text-sm text-slate-600 hover:bg-slate-50"
        >
          <span className="font-medium">
            {context.company || "Target"} &middot;{" "}
            {AUDIENCE_LABELS[context.audienceType]} &middot;{" "}
            {context.messageFormat}
          </span>
          <span className="text-xs text-slate-400">
            {contextExpanded ? "Hide" : "Show"} details
          </span>
        </button>
        {contextExpanded && (
          <div className="border-t border-slate-100 px-4 py-3">
            <div className="flex flex-wrap gap-2">
              {context.jobTitle && (
                <span className="inline-flex items-center rounded-full bg-cyan-50 px-2.5 py-0.5 text-xs font-medium text-cyan-700">
                  {context.jobTitle}
                </span>
              )}
              <span className="inline-flex items-center rounded-full bg-indigo-50 px-2.5 py-0.5 text-xs font-medium text-indigo-700">
                {AUDIENCE_LABELS[context.audienceType]}
              </span>
              <span className="inline-flex items-center rounded-full bg-slate-100 px-2.5 py-0.5 text-xs font-medium text-slate-600">
                {context.messageFormat}
              </span>
              {context.userName && (
                <span className="inline-flex items-center rounded-full bg-emerald-50 px-2.5 py-0.5 text-xs font-medium text-emerald-700">
                  From: {context.userName}
                </span>
              )}
            </div>
            {context.purpose && (
              <p className="mt-2 text-xs text-slate-500">{context.purpose}</p>
            )}
          </div>
        )}
      </div>

      {/* Chat messages */}
      <div
        ref={chatContainerRef}
        onScroll={handleScroll}
        className="max-h-[55vh] overflow-y-auto rounded-lg border border-slate-200 bg-slate-50 p-4 space-y-4"
      >
        {messages.map((msg, i) => (
          <div
            key={i}
            className={`flex ${msg.role === "user" ? "justify-end" : "justify-start"}`}
          >
            <div
              className={`max-w-[85%] rounded-lg px-4 py-3 text-sm ${
                msg.role === "user"
                  ? "bg-cyan-600 text-white"
                  : "bg-white border border-slate-200 text-slate-800"
              }`}
            >
              {msg.role === "assistant" && (
                <div className="flex items-center justify-between mb-1">
                  <span className="text-xs font-medium text-cyan-600">
                    Outreach Crafter
                  </span>
                  <button
                    type="button"
                    onClick={() => handleCopy(msg.content, i)}
                    className="ml-3 text-xs text-slate-400 hover:text-slate-600 transition-colors"
                  >
                    {copiedIndex === i ? "Copied!" : "Copy message"}
                  </button>
                </div>
              )}
              <p className="whitespace-pre-wrap">{msg.content}</p>
            </div>
          </div>
        ))}
        {isLoading && messages[messages.length - 1]?.role !== "assistant" && (
          <div className="flex justify-start">
            <div className="rounded-lg bg-white border border-slate-200 px-4 py-3">
              <div className="flex gap-1">
                <span
                  className="h-2 w-2 rounded-full bg-slate-300 animate-bounce"
                  style={{ animationDelay: "0ms" }}
                />
                <span
                  className="h-2 w-2 rounded-full bg-slate-300 animate-bounce"
                  style={{ animationDelay: "150ms" }}
                />
                <span
                  className="h-2 w-2 rounded-full bg-slate-300 animate-bounce"
                  style={{ animationDelay: "300ms" }}
                />
              </div>
            </div>
          </div>
        )}
        <div ref={chatEndRef} />
      </div>

      {/* Input */}
      <div className="flex gap-2">
        <textarea
          value={input}
          onChange={(e) => setInput(e.target.value)}
          onKeyDown={handleKeyDown}
          placeholder="Refine: &quot;make it shorter&quot;, &quot;more casual&quot;, &quot;mention my ML experience&quot;..."
          disabled={isLoading}
          rows={2}
          className="flex-1 resize-none rounded-lg border border-slate-300 px-4 py-3 text-sm focus:border-cyan-500 focus:outline-none focus:ring-1 focus:ring-cyan-500 disabled:opacity-50"
        />
        <button
          type="button"
          onClick={handleSend}
          disabled={isLoading || !input.trim()}
          className="rounded-lg bg-cyan-600 px-4 py-2 text-sm font-medium text-white hover:bg-cyan-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors self-end"
        >
          Send
        </button>
      </div>
    </div>
  );
}
